### ISSUE TITLE
Mask missing photometry

### ISSUE THREAD

**Issue by gbrammer** [RashmiGot/dja-pipes#5]
I got an error when trying to run `fname = 'uncover-61-v3_prism-clear_2561_13416'`: 
```python
ValueError: 'yerr' must not contain negative values
```

I think the F090W band might be missing for that source, so be sure to check that the photometry is valid in all bands from the query.  A simple test for "valid" photometry is `({filter}_tot_1 > -90) & ({filter}_etot_1 > 0)`.

**Comment by RashmiGot** [comment]
Hi Gabe,

I've added a flux mask to check for valid photometry when plotting. The code runs now for `fname = 'uncover-61-v3_prism-clear_2561_13416'`.

**Comment by RashmiGot** [comment]
Hi Gabe,

I've added a flux mask to check for valid photometry when plotting. The code runs now for `fname = 'uncover-61-v3_prism-clear_2561_13416'`.
